import { createListingStatus } from "../PropertyCardList/listingStatus";
import type { PropertyListing } from "../PropertyCardList/types";

const sampleImages = [
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop",
];

function buildProperty(
  id: number,
  title: string,
  price: string,
  overrides: Partial<PropertyListing> = {},
): PropertyListing {
  const referenceNumber = `REF-${String(id).padStart(4, "0")}`;

  return {
    id,
    property_id: `81316c83-${String(id).padStart(4, "0")}-story-0000-000000000001`,
    property_hash: String(500000000 + id),
    reference_number: referenceNumber,
    title: { en: title, ar: title, esp: title, fr: title },
    description: { en: `${title} description`, ar: null, esp: null, fr: null },
    price,
    status: createListingStatus("verified"),
    category: "Residential",
    searchPropertyType: "villa",
    city: "Amman",
    areaName: "Abdoun",
    propertyType: "Villa",
    media: {
      thumbnail: sampleImages[0]!,
      images: sampleImages.map((url, index) => ({
        id: index + 1,
        url,
        thumb_url: url,
        is_primary: index === 0,
        order: index,
        caption: null,
      })),
      videos: [],
      virtual_tour_url: null,
      floor_plan_images: [],
      documents: [],
    },
    location: {
      country_id: 1,
      country: "Jordan",
      city_id: 1,
      city: "Amman",
      region_id: 1,
      region: "Abdoun",
      address: { en: "Abdoun", ar: "Abdoun", esp: "Abdoun", fr: "Abdoun" },
      latitude: 31.9488329,
      longitude: 35.8926603,
      map_embed_url: "https://maps.google.com/?q=31.9488329,35.8926603",
    },
    location_detail: {
      country_id: 1,
      country: "Jordan",
      city_id: 1,
      city: "Amman",
      region_id: 1,
      region: "Abdoun",
      address: { en: "Abdoun", ar: "Abdoun", esp: "Abdoun", fr: "Abdoun" },
      latitude: 31.9488329,
      longitude: 35.8926603,
      map_embed_url: "https://maps.google.com/?q=31.9488329,35.8926603",
    },
    beds: 4,
    baths: 3,
    area: "3200",
    acres: null,
    highlights: "Garden · Parking",
    badges: ["For Sale"],
    handover: null,
    paymentPlan: null,
    validatedDate: "2026-01-15",
    brokerName: "Abdoun Real Estate",
    brokerLogo: null,
    agent: {
      id: 21,
      name: "Steven G. Copeland",
      phone: "+962791234567",
      whatsapp: "+962791234567",
      email: "steven.copeland@example.com",
      photo: null,
      license_number: null,
    },
    owners: [],
    is_exclusive: true,
    is_favourite: false,
    ...overrides,
  };
}

export const listTableStoryListings: PropertyListing[] = [
  buildProperty(301, "Modern Villa with Garden", "JOD 450,000", {
    status: createListingStatus("verified", "Verified"),
    areaName: "Abdoun",
    city: "Amman",
    submitted_on: "2026-03-01T10:30:00.000000Z",
    submission_submitted_by: "Steven G. Copeland",
    actions: [{ id: "view" }, { id: "assign" }, { id: "reassign" }],
  }),
  buildProperty(302, "Luxury Apartment in Abdoun", "JOD 320,000", {
    propertyType: "Apartment",
    area: "1850",
    beds: 3,
    baths: 2,
    areaName: "Abdoun",
    city: "Amman",
    status: createListingStatus("pending_approval", "Pending approval"),
    submitted_on: "2026-02-18T14:15:00.000000Z",
    submission_submitted_by: "Nadia Rahman",
    actions: [{ id: "view" }, { id: "reassign" }, { id: "unassign" }],
  }),
  buildProperty(303, "Family Home with Terrace", "JOD 280,000", {
    areaName: "Khalda",
    city: "Amman",
    propertyType: "Townhouse",
    beds: 4,
    baths: 3,
    status: createListingStatus("active", "Active"),
    submitted_on: "2026-01-22T09:00:00.000000Z",
    submission_submitted_by: "Khalda Properties",
    agency: {
      agency_id: 12,
      agency_name: "Khalda Properties",
      email: "listings@khalda.example",
      phone: "+96265551234",
    },
    actions: [{ id: "view" }, { id: "assign" }],
  }),
  buildProperty(304, "Penthouse with Panoramic Views", "JOD 620,000", {
    propertyType: "Penthouse",
    areaName: "Abdoun",
    city: "Amman",
    beds: 5,
    baths: 4,
    status: createListingStatus("rejected", "Rejected"),
    submitted_on: "2026-03-10T16:45:00.000000Z",
    submission_submitted_by: "Abdoun Realty",
    submission_review_reason:
      "Floor plan images are missing from the submission package.",
    agency: {
      agency_id: 1,
      agency_name: "Abdoun Realty",
      email: "submissions@abdoun.example",
      phone: "+96265559876",
    },
    actions: [
      { id: "view" },
      { id: "rejected_reason" },
      { id: "reassign" },
      { id: "unassign" },
    ],
  }),
  buildProperty(305, "Cozy Studio in Shmeisani", "JOD 125,000", {
    areaName: "Shmeisani",
    city: "Amman",
    propertyType: "Studio",
    beds: 1,
    baths: 1,
    area: "650",
    status: createListingStatus("changes_requested", "Changes requested"),
    submitted_on: "2026-02-05T11:20:00.000000Z",
    submission_submitted_by: "Layla Mansour",
    actions: [{ id: "view" }, { id: "continue" }],
  }),
];
